---
title: "Perusall Quick-Start Guide"
author: ""
date: "`r format(Sys.Date(), '%B %Y')`"
description: "This is a tutorial for using Perusall"
github-repo: "IQSS/dss-perusall"
site: "bookdown::bookdown_site"
documentclass: book
geometry: "margin=1.5in"
biblio-style: apalike
link-citations: yes
---

# What is Perusall? {-}

[Perusal](https://perusall.com/) is a browser-based software platform for interactive learning.


# Why are we using Perusall? {-}

Some of our Data Science Workshops are being taught using a "flipped classroom" model --- this is where lecture-based material is delivered asyncronously so that it can be digested at your own pace, which provides more time for Q&A discussion during in-class time. 

Prior to our Zoom-based 1 hour Q&A session, there will be a **two week self-study period** within which you can work through the workshop materials at your own pace. We are using Persuall as a means to facilitate greater engagement with the workshop materials during this self-study period. Using Perusall, you will be able to post questions and comments about parts of the materials you do not understand or problems you encounter. Instructors can answer your questions and comments, but you will also have the opportunity to reply to questions and comments from other participants. In this way, Perusall facilitates peer-to-peer and peer-to-instructor learning.

**Your successful completion of the workshop will be based on making a contribution, via questions and comments, during this self-study period.**


# How to use Perusall? {-}

You should have received an email asking you to create an account at https://perusall.com/. You should also have receive a course code via email. If you have not, please contact your workshop administrator. Once your Perusall account is created, enter the course code and you will be able to view the course materials. 

During the two week self-study period, you can highlight sections of the workshop materials you wish to ask questions about, make comments, as well as respond to questions and comments from other participants. The window for submitting questions will close 24 hours prior to the Zoom Q&A session.

## Perusall layout


## How to highlight text


## How to ask a question


## How to answer a question



### Authors and Sources {-}

This tutorial was created by Steven Worthington at IQSS.
